[workspace]
resolver = "2"
members = [
  "hiisi-server",
  "hiisi-simulator",
]
default-members = [
  "hiisi-server",
]

[workspace.package]
version = "0.0.0"
authors = ["the Hiisi authors"]
edition = "2021"
license = "MIT"
repository = "https://github.com/penberg/hiisi"
